#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export REPO_ROOT="${REPO_ROOT:-$(cd -- "$SCRIPT_DIR/../../.." && pwd)}"

export LAZYMIND_LOCAL_ALGO_ROOT="${LAZYMIND_LOCAL_ALGO_ROOT:-$REPO_ROOT/.lazymind-local/algo}"
export LAZYMIND_LOCAL_ALGO_VENV="${LAZYMIND_LOCAL_ALGO_VENV:-$LAZYMIND_LOCAL_ALGO_ROOT/.venv}"

export LAZYMIND_LOCAL_ALGO_HOST="${LAZYMIND_LOCAL_ALGO_HOST:-0.0.0.0}"
export LAZYMIND_LOCAL_ALGO_PUBLIC_HOST="${LAZYMIND_LOCAL_ALGO_PUBLIC_HOST:-127.0.0.1}"

export LAZYMIND_LOCAL_DOC_SERVER_PORT="${LAZYMIND_LOCAL_DOC_SERVER_PORT:-18080}"
export LAZYMIND_LOCAL_PROCESSOR_SERVER_PORT="${LAZYMIND_LOCAL_PROCESSOR_SERVER_PORT:-18081}"
export LAZYMIND_LOCAL_PROCESSOR_WORKER_PORT="${LAZYMIND_LOCAL_PROCESSOR_WORKER_PORT:-18082}"
export LAZYMIND_LOCAL_ALGO_PORT="${LAZYMIND_LOCAL_ALGO_PORT:-18083}"
export LAZYMIND_LOCAL_CHAT_ROUTER_PORT="${LAZYMIND_LOCAL_CHAT_ROUTER_PORT:-18084}"

export LAZYMIND_LOCAL_POSTGRES_PORT="${LAZYMIND_LOCAL_POSTGRES_PORT:-15432}"
export LAZYMIND_LOCAL_REDIS_PORT="${LAZYMIND_LOCAL_REDIS_PORT:-16379}"
export LAZYMIND_LOCAL_MILVUS_PORT="${LAZYMIND_LOCAL_MILVUS_PORT:-19530}"
export LAZYMIND_LOCAL_OPENSEARCH_PORT="${LAZYMIND_LOCAL_OPENSEARCH_PORT:-19200}"
export LAZYMIND_LOCAL_CORE_PORT="${LAZYMIND_LOCAL_CORE_PORT:-18000}"

export LAZYMIND_LOCAL_ALGO_LOG_DIR="$LAZYMIND_LOCAL_ALGO_ROOT/logs"
export LAZYMIND_LOCAL_ALGO_RUN_DIR="$LAZYMIND_LOCAL_ALGO_ROOT/run"
export LAZYMIND_LOCAL_ALGO_PYTHON="${LAZYMIND_LOCAL_ALGO_VENV}/bin/python"
export LAZYMIND_HOME="$LAZYMIND_LOCAL_ALGO_ROOT/home"

export LAZYMIND_DOCUMENT_PROCESSOR_PORT="${LAZYMIND_LOCAL_PROCESSOR_SERVER_PORT}"
export LAZYMIND_DOCUMENT_WORKER_PORT="${LAZYMIND_LOCAL_PROCESSOR_WORKER_PORT}"
export LAZYMIND_ALGO_SERVER_PORT="${LAZYMIND_LOCAL_ALGO_PORT}"
export LAZYMIND_DOCUMENT_SERVICE_PORT="${LAZYMIND_LOCAL_DOC_SERVER_PORT}"

export PYTHONPATH="$REPO_ROOT/algorithm/lazyllm:$REPO_ROOT/algorithm:$REPO_ROOT"

export LAZYMIND_RUNTIME_MODE=local
export LAZYMIND_LOCAL_PROFILE=algo-host

export LAZYMIND_DATABASE_URL="postgresql+psycopg://app:app@127.0.0.1:${LAZYMIND_LOCAL_POSTGRES_PORT}/app"
export LAZYMIND_CORE_DATABASE_URL="postgresql://root:123456@127.0.0.1:${LAZYMIND_LOCAL_POSTGRES_PORT}/core"

export LAZYMIND_DOCUMENT_PROCESSOR_URL="http://127.0.0.1:${LAZYMIND_LOCAL_PROCESSOR_SERVER_PORT}"
export LAZYMIND_DOCUMENT_SERVER_URL="http://127.0.0.1:${LAZYMIND_LOCAL_ALGO_PORT}"
export LAZYMIND_CHAT_DOCUMENT_SERVER_URL="http://127.0.0.1:${LAZYMIND_LOCAL_ALGO_PORT},general_algo"
export LAZYMIND_AGENTIC_KB_URL="http://127.0.0.1:${LAZYMIND_LOCAL_ALGO_PORT}"
export LAZYMIND_CORE_API_URL="http://127.0.0.1:${LAZYMIND_LOCAL_CORE_PORT}"
export LAZYMIND_CORE_SERVICE_URL="http://127.0.0.1:${LAZYMIND_LOCAL_CORE_PORT}"
export LAZYMIND_MILVUS_URI="http://127.0.0.1:${LAZYMIND_LOCAL_MILVUS_PORT}"
export LAZYMIND_SEGMENT_STORE_TYPE=opensearch
export LAZYMIND_SEGMENT_STORE_URI_OR_PATH="https://127.0.0.1:${LAZYMIND_LOCAL_OPENSEARCH_PORT}"
export LAZYMIND_SEGMENT_STORE_USER=admin
export LAZYMIND_SEGMENT_STORE_PASSWORD="${LAZYMIND_SEGMENT_STORE_PASSWORD:-LazyRAG_OpenSearch123!}"

export LAZYMIND_SHARED_UPLOAD_DIR="$REPO_ROOT/data/core/uploads"
export LAZYMIND_UPLOAD_ROOT="$REPO_ROOT/data/core/uploads"
export LAZYMIND_UPLOAD_DIR="$REPO_ROOT/data/core/uploads"
export LAZYMIND_CONTAINER_UPLOAD_ROOT="${LAZYMIND_CONTAINER_UPLOAD_ROOT:-/var/lib/lazymind/uploads}"
export LAZYMIND_HOST_UPLOAD_ROOT="${LAZYMIND_HOST_UPLOAD_ROOT:-$REPO_ROOT/data/core/uploads}"
export LAZYLLM_TEMP_DIR="$REPO_ROOT/data/core/uploads/.lazyllm_temp"
export LAZYMIND_OCR_CACHE_DIR="$REPO_ROOT/data/core/uploads/.image_cache"
export LAZYLLM_TRACE_LOCAL_STORAGE_DIR="$REPO_ROOT/data/traces"
export LAZYMIND_MODEL_CONFIG_PATH="${LAZYMIND_MODEL_CONFIG_PATH:-dynamic}"
export LAZYMIND_USE_INNER_MODEL=true
export LAZYMIND_ENABLE_ROUTER="${LAZYMIND_ENABLE_ROUTER:-true}"
export LAZYMIND_ROUTER_PORT_POOL_START=18100
export LAZYMIND_ROUTER_PORT_POOL_END=18199
export LAZYMIND_ROUTER_PORTS_PER_INSTANCE=100
export LAZYMIND_ROUTER_DEFAULT_ALGO_PATH="$REPO_ROOT/algorithm/lazymind/chat"
export LAZYMIND_ROUTER_DEFAULT_INSTANCE_COUNT=1
export LAZYMIND_PLUGINS_DIR="$REPO_ROOT/plugins"
