import { DeleteOutlined, EditOutlined, PlusOutlined, RobotOutlined, StopOutlined } from "@ant-design/icons";
import { Alert, Button, Checkbox, Empty, Form, Input, List, Modal, Popconfirm, Segmented, Select, Space, Spin, Tag, Tooltip, Typography, message } from "antd";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { getLocalizedErrorMessage } from "@/components/request";
import type { PdfTextSelection } from "@/components/ui";
import { cancelPreanalysisTask, createPreanalysisTask, deleteLearningPreset, getLatestPreanalysisTask, getPreanalysisTask, listLearningPresets, listPreanalysisDrafts, publishPreanalysisDrafts, putLearningPreset, runPreanalysisTask, updateLearningPreset, type LearningCapability, type LearningPreset, type PreanalysisTask } from "./api";
import "./DocumentLearningPanel.scss";

interface Props { datasetId:string;documentId:string;revision?:string;capabilities:LearningCapability[];localAvailable:boolean;analysisSelection?:PdfTextSelection&{requestId:number} }
type Drafts={presets:LearningPreset[];contents:Record<string,unknown>[]};

const parseValue=(raw:string)=>{try{return JSON.parse(raw||"{}") as Record<string,unknown>}catch{return {}}};
const displayText=(value:unknown):string=>{if(typeof value==="string"||typeof value==="number")return String(value).trim();if(value&&typeof value==="object"){const row=value as Record<string,unknown>;const sentence=displayText(row.sentence??row.text??row.example);const translation=displayText(row.translation);return [sentence,translation].filter(Boolean).join(" — ")}return ""};
export const presetDisplayValue=(raw:string)=>{const value=parseValue(raw);const semanticKeys=["meaning_in_context","meaning","definition","translation"];const semantic=semanticKeys.map(key=>displayText(value[key])).find(Boolean)||Object.entries(value).filter(([key])=>!["examples","example","phonetic","pinyin","citations"].includes(key)).map(([,item])=>displayText(item)).find(Boolean)||"";const rawExamples=value.examples??value.example;const examples=(Array.isArray(rawExamples)?rawExamples:[rawExamples]).map(displayText).filter(Boolean);return {semantic,examples}};
export const displayPresetKey=(key:string)=>{const parts=key.split("\x1f");return parts[0]==="learning-v1"&&parts.length>=5?parts[4]:key};

export default function DocumentLearningPanel({datasetId,documentId,revision,capabilities,localAvailable,analysisSelection}:Props){
 const {t}=useTranslation(); const [presets,setPresets]=useState<LearningPreset[]>([]); const [filter,setFilter]=useState("all"); const [selectedPresets,setSelectedPresets]=useState<string[]>([]); const [editor,setEditor]=useState<{preset?:LearningPreset;open:boolean}>({open:false}); const [analysisOpen,setAnalysisOpen]=useState(Boolean(analysisSelection)); const [selected,setSelected]=useState<string[]>(capabilities.map(x=>x.key)); const [analysisScope,setAnalysisScope]=useState<"document"|"selection">(analysisSelection?"selection":"document"); const [analysisText,setAnalysisText]=useState(analysisSelection?.text||""); const [analysisPage,setAnalysisPage]=useState<number|undefined>(analysisSelection?.page); const [analysisDirection,setAnalysisDirection]=useState(""); const [task,setTask]=useState<PreanalysisTask>(); const [drafts,setDrafts]=useState<Drafts>(); const [selectedDrafts,setSelectedDrafts]=useState<string[]>([]); const [starting,setStarting]=useState(false); const [stopping,setStopping]=useState(false); const [publishing,setPublishing]=useState(false); const [loading,setLoading]=useState(false); const [deleting,setDeleting]=useState(false); const [form]=Form.useForm();
 const capabilityMap=useMemo(()=>new Map(capabilities.map(item=>[item.key,item])),[capabilities]);
 const capabilityLabel=(key:string)=>{const item=capabilityMap.get(key);return item?t(item.name_i18n_key):key};
 const presetValue=(item:LearningPreset)=>{const display=presetDisplayValue(item.value_json);const detail=<div className="document-analysis__value-tooltip"><div><strong>{t("learning.field.meaningInContext")}</strong><div>{display.semantic||"—"}</div></div>{display.examples.length?<div className="document-analysis__value-examples"><strong>{t("learning.field.examples")}</strong><ul>{display.examples.map((example,index)=><li key={`${index}-${example}`}>{example}</li>)}</ul></div>:null}</div>;return <Tooltip title={detail} placement="left"><Typography.Paragraph className="document-analysis__value" ellipsis={{rows:2}}>{display.semantic||"—"}</Typography.Paragraph></Tooltip>};
 const load=async()=>{if(!localAvailable)return;setLoading(true);try{setPresets(await listLearningPresets("document",documentId))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[documentId,localAvailable]);
 useEffect(()=>{let active=true;if(!localAvailable)return()=>{active=false};getLatestPreanalysisTask(datasetId,documentId).then(latest=>{if(active)setTask(latest)}).catch(()=>{});return()=>{active=false}},[datasetId,documentId,localAvailable]);
 const taskActive=starting||task?.status==="queued"||task?.status==="running";
 useEffect(()=>{if(!task||!["queued","running"].includes(task.status))return;let active=true;const poll=async()=>{try{const next=await getPreanalysisTask(task.id);if(active)setTask(next)}catch{/* Keep the last authoritative state and retry. */}};const timer=window.setInterval(()=>void poll(),1000);void poll();return()=>{active=false;window.clearInterval(timer)}},[task?.id,task?.status]);
 useEffect(()=>{if(!task||!["completed","completed_with_errors"].includes(task.status))return;let active=true;listPreanalysisDrafts(task.id).then(found=>{if(!active)return;setDrafts(found);setSelectedDrafts(found.presets.map(x=>x.id))}).catch(()=>{});return()=>{active=false}},[task?.id,task?.status]);
 useEffect(()=>setSelected(capabilities.map(x=>x.key)),[capabilities]);
 useEffect(()=>{if(!analysisSelection)return;setAnalysisScope("selection");setAnalysisText(analysisSelection.text);setAnalysisPage(analysisSelection.page);setDrafts(undefined);setAnalysisOpen(true)},[analysisSelection?.requestId]);
 const counts=useMemo(()=>presets.reduce<Record<string,number>>((out,row)=>{out[row.capability_key]=(out[row.capability_key]||0)+1;return out},{}),[presets]);
 const visible=filter==="all"?presets:presets.filter(row=>row.capability_key===filter);
 const visibleIds=visible.map(row=>row.id); const visibleSelected=visibleIds.filter(id=>selectedPresets.includes(id));
 const allVisibleSelected=visibleIds.length>0&&visibleSelected.length===visibleIds.length;
 const openCreate=()=>{form.resetFields();form.setFieldsValue({capability_key:capabilities[0]?.key});setEditor({open:true})};
 const openEdit=(preset:LearningPreset)=>{form.setFieldsValue({capability_key:preset.capability_key,key:preset.normalized_key,...parseValue(preset.value_json)});setEditor({open:true,preset})};
 const save=async()=>{const values=await form.validateFields();const capability=capabilityMap.get(values.capability_key);if(!capability)return;const content=Object.fromEntries(capability.fields.map(field=>[field.key,values[field.key]]).filter(([,value])=>value!==undefined&&value!==""));if(editor.preset)await updateLearningPreset(editor.preset.id,content,editor.preset.priority);else await putLearningPreset({scope_type:"document",scope_id:documentId,document_revision:revision||"",capability_key:values.capability_key,key:values.key,value:content,origin:"user"});message.success(t("common.saveSuccess"));setEditor({open:false});await load()};
 const remove=async(id:string)=>{await deleteLearningPreset(id);message.success(t("common.success"));await load()};
 const removeMany=async(ids:string[])=>{if(!ids.length)return;setDeleting(true);try{const results=await Promise.allSettled(ids.map(id=>deleteLearningPreset(id)));const deletedIds=ids.filter((_,index)=>results[index].status==="fulfilled");const failed=ids.length-deletedIds.length;setSelectedPresets(current=>current.filter(id=>!deletedIds.includes(id)));await load();if(failed)message.warning(t("learning.batchDeletePartial",{deleted:deletedIds.length,failed}));else message.success(t("learning.batchDeleteSuccess",{count:deletedIds.length}))}finally{setDeleting(false)}};
 const confirmRemoveMany=(ids:string[],all=false)=>Modal.confirm({title:t(all?"learning.deleteAllPresetConfirm":"learning.batchDeletePresetConfirm",{count:ids.length}),content:t("learning.deletePresetsWarning"),okText:t("common.delete"),okButtonProps:{danger:true},cancelText:t("common.cancel"),onOk:()=>removeMany(ids)});
 const analyze=async()=>{const paragraphs=analysisScope==="selection"?analysisText.split(/\n\s*\n/u).map(text=>text.trim()).filter(Boolean):[];setAnalysisOpen(false);setStarting(true);setDrafts(undefined);try{const created=await createPreanalysisTask({dataset_id:datasetId,document_id:documentId,document_revision:revision,capability_keys:selected,analysis_direction:analysisDirection.trim()||undefined,items:paragraphs.length?paragraphs.map(text=>({text,context:text,page:analysisPage})):undefined});setTask(created);await runPreanalysisTask(created.id)}catch(e){setTask(undefined);message.error(getLocalizedErrorMessage(e))}finally{setStarting(false)}};
 const stopAnalysis=async()=>{if(!task)return;setStopping(true);try{setTask(await cancelPreanalysisTask(task.id));message.success(t("learning.preanalysisCanceled"))}catch(e){message.error(getLocalizedErrorMessage(e))}finally{setStopping(false)}};
 const confirmStopAnalysis=()=>Modal.confirm({title:t("learning.cancelPreanalysisConfirm"),okText:t("learning.stopAnalysis"),okButtonProps:{danger:true},cancelText:t("common.cancel"),onOk:stopAnalysis});
 const publish=async()=>{if(!task||!drafts||!selectedDrafts.length)return;setPublishing(true);try{await publishPreanalysisDrafts(task.id,revision||"",selectedDrafts,[]);const remaining=await listPreanalysisDrafts(task.id);setDrafts(remaining);setSelectedDrafts(remaining.presets.map(item=>item.id));message.success(t("learning.preanalysisPublished"));await load()}catch(e){message.error(getLocalizedErrorMessage(e))}finally{setPublishing(false)}};
 const editingCapability=capabilityMap.get(Form.useWatch("capability_key",form));
 return <div className="document-analysis">
  {!localAvailable?<Alert type="warning" showIcon message={t("vocabulary.localOnlyDesktop")}/>:null}
  <div className="document-analysis__header"><div><Typography.Title level={4}>{t("learning.presetAnswers")}</Typography.Title><Typography.Text type="secondary">{t("learning.presetAnswersHint")}</Typography.Text></div><Space align="start"><div className="document-analysis__analysis-action"><div className="document-analysis__analysis-buttons"><Button icon={<RobotOutlined/>} disabled={!localAvailable||taskActive} loading={starting} onClick={()=>setAnalysisOpen(true)}>{t("learning.aiGenerate")}</Button>{taskActive&&task?.id?<Button danger icon={<StopOutlined/>} loading={stopping} onClick={confirmStopAnalysis}>{t("learning.stopAnalysis")}</Button>:null}</div>{task||starting?<Typography.Text type="secondary" className="document-analysis__status">{task?t("learning.preanalysisStatus",{status:task.status,completed:task.completed,failed:task.failed}):t("learning.analysisPreparing")}</Typography.Text>:null}{task?.error_message?<Typography.Paragraph type="danger" className="document-analysis__error" ellipsis={{rows:3,expandable:true,symbol:t("common.expand")}}>{t("learning.preanalysisFailureDetail",{reason:task.error_message})}</Typography.Paragraph>:null}</div><Button type="primary" icon={<PlusOutlined/>} disabled={!localAvailable} onClick={openCreate}>{t("learning.addPresetAnswer")}</Button></Space></div>
  {drafts?.presets.length?<section className="document-analysis__pending"><div className="document-analysis__pending-header"><div><Typography.Title level={5}>{t("learning.pendingAnswers",{count:drafts.presets.length})}</Typography.Title><Typography.Text type="secondary">{t("learning.pendingAnswersHint")}</Typography.Text></div><Button type="primary" loading={publishing} disabled={!selectedDrafts.length} onClick={()=>void publish()}>{t("learning.confirmSelected",{count:selectedDrafts.length})}</Button></div><Checkbox indeterminate={selectedDrafts.length>0&&selectedDrafts.length<drafts.presets.length} checked={selectedDrafts.length===drafts.presets.length} onChange={event=>setSelectedDrafts(event.target.checked?drafts.presets.map(item=>item.id):[])}>{t("common.selectAll")}</Checkbox><List className="document-analysis__drafts" dataSource={drafts.presets} renderItem={item=><List.Item><Checkbox checked={selectedDrafts.includes(item.id)} onChange={event=>setSelectedDrafts(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}><Typography.Text strong>{displayPresetKey(item.normalized_key)}</Typography.Text><Tag>{capabilityLabel(item.capability_key)}</Tag>{presetValue(item)}</Checkbox></List.Item>}/></section>:null}
  <Segmented className="document-analysis__filters" value={filter} onChange={value=>setFilter(String(value))} options={[{value:"all",label:`${t("common.all")} ${presets.length}`},...capabilities.filter(item=>counts[item.key]).map(item=>({value:item.key,label:`${t(item.name_i18n_key)} ${counts[item.key]}`}))]}/>
  {presets.length?<div className="document-analysis__bulk-actions"><Checkbox checked={allVisibleSelected} indeterminate={visibleSelected.length>0&&!allVisibleSelected} onChange={event=>setSelectedPresets(current=>event.target.checked?Array.from(new Set([...current,...visibleIds])):current.filter(id=>!visibleIds.includes(id)))}>{t("learning.selectVisible",{count:visibleSelected.length})}</Checkbox><Space><Button danger disabled={!selectedPresets.length||deleting} loading={deleting} onClick={()=>confirmRemoveMany(selectedPresets)}>{t("learning.batchDelete",{count:selectedPresets.length})}</Button><Button danger disabled={deleting} onClick={()=>confirmRemoveMany(presets.map(item=>item.id),true)}>{t("learning.deleteAll")}</Button></Space></div>:null}
  <Spin spinning={loading}><List className="document-analysis__list" dataSource={visible} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t("learning.noPresetAnswers")}/>}} renderItem={item=><List.Item actions={[<Button key="edit" type="text" icon={<EditOutlined/>} aria-label={t("common.edit")} onClick={()=>openEdit(item)}/>,<Popconfirm key="delete" title={t("learning.deletePresetConfirm")} onConfirm={()=>void remove(item.id)}><Button type="text" danger icon={<DeleteOutlined/>} aria-label={t("common.delete")}/></Popconfirm>]}><Checkbox className="document-analysis__item-checkbox" aria-label={t("learning.selectPreset",{name:displayPresetKey(item.normalized_key)})} checked={selectedPresets.includes(item.id)} onChange={event=>setSelectedPresets(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}/><List.Item.Meta title={<Space><Typography.Text strong>{displayPresetKey(item.normalized_key)}</Typography.Text><Tag>{capabilityLabel(item.capability_key)}</Tag></Space>} description={<>{presetValue(item)}<Typography.Text type="secondary" className="document-analysis__origin">{item.origin==="user"?t("learning.manuallyAdded"):t("learning.aiGenerated")}</Typography.Text></>}/></List.Item>}/></Spin>
  <Modal open={editor.open} title={editor.preset?t("learning.editPresetAnswer"):t("learning.addPresetAnswer")} onCancel={()=>setEditor({open:false})} onOk={()=>void save()} okText={t("common.save")} destroyOnHidden><Form form={form} layout="vertical"><Form.Item name="capability_key" label={t("learning.answerType")} rules={[{required:true}]}><Select disabled={!!editor.preset} options={capabilities.map(item=>({value:item.key,label:t(item.name_i18n_key)}))}/></Form.Item><Form.Item name="key" label={t("learning.matchContent")} extra={t("learning.matchContentHint")} rules={[{required:true}]}><Input disabled={!!editor.preset}/></Form.Item>{editingCapability?.fields.map(field=><Form.Item key={field.key} name={field.key} label={t(field.label_i18n_key)} rules={field.required?[{required:true,message:t("learning.requiredField")}]:undefined}>{field.type==="string_list"?<Select mode="tags" tokenSeparators={[",","，"]}/>:field.type==="text"?<Input.TextArea rows={4}/>:<Input/>}</Form.Item>)}</Form></Modal>
  <Modal open={analysisOpen} title={t("learning.aiAnalysisTitle")} width={720} onCancel={()=>setAnalysisOpen(false)} footer={null}>
   <div className="document-analysis__generator"><RobotOutlined/><Typography.Title level={5}>{t("learning.chooseAnalysisCapabilities")}</Typography.Title><Typography.Text type="secondary">{t("learning.chooseAnalysisCapabilitiesHint")}</Typography.Text><label>{t("learning.analysisScope")}</label><Segmented block value={analysisScope} onChange={value=>setAnalysisScope(value as "document"|"selection")} options={[{value:"document",label:t("learning.wholeDocument")},{value:"selection",label:t("learning.selectedParagraphs")}]} />{analysisScope==="selection"?<Input.TextArea value={analysisText} onChange={event=>setAnalysisText(event.target.value)} autoSize={{minRows:4,maxRows:10}} placeholder={t("learning.selectedParagraphsPlaceholder")} showCount maxLength={12000}/>:null}<label>{t("learning.analysisCapabilities")}</label><Select mode="multiple" value={selected} onChange={setSelected} options={capabilities.map(x=>({value:x.key,label:t(x.name_i18n_key)}))}/><label>{t("learning.analysisDirection")}</label><Input.TextArea value={analysisDirection} onChange={event=>setAnalysisDirection(event.target.value)} autoSize={{minRows:2,maxRows:5}} maxLength={1000} showCount placeholder={t("learning.analysisDirectionPlaceholder")}/><Button type="primary" disabled={!selected.length||(analysisScope==="selection"&&!analysisText.trim())} onClick={()=>void analyze()}>{t("learning.startAnalysis")}</Button></div>
  </Modal>
 </div>
}
