import { DeleteOutlined, EditOutlined, PlusOutlined, RobotOutlined } from "@ant-design/icons";
import { Alert, Button, Checkbox, Empty, Form, Input, List, Modal, Popconfirm, Segmented, Select, Space, Spin, Tag, Typography, message } from "antd";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { createPreanalysisTask, deleteLearningPreset, getPreanalysisTask, listLearningPresets, listPreanalysisDrafts, publishPreanalysisDrafts, putLearningPreset, runPreanalysisTask, updateLearningPreset, type LearningCapability, type LearningPreset } from "./api";
import "./DocumentLearningPanel.scss";

interface Props { datasetId:string;documentId:string;revision?:string;capabilities:LearningCapability[];localAvailable:boolean }
type Drafts={presets:LearningPreset[];contents:Record<string,unknown>[]};

const parseValue=(raw:string)=>{try{return JSON.parse(raw||"{}") as Record<string,unknown>}catch{return {}}};
const valueSummary=(raw:string)=>Object.values(parseValue(raw)).flatMap(value=>Array.isArray(value)?value:[value]).filter(Boolean).map(String).join(" · ");

export default function DocumentLearningPanel({datasetId,documentId,revision,capabilities,localAvailable}:Props){
 const {t}=useTranslation(); const [presets,setPresets]=useState<LearningPreset[]>([]); const [filter,setFilter]=useState("all"); const [editor,setEditor]=useState<{preset?:LearningPreset;open:boolean}>({open:false}); const [selected,setSelected]=useState<string[]>(capabilities.map(x=>x.key)); const [task,setTask]=useState<{id:string;status:string;total:number;completed:number;failed:number}>(); const [drafts,setDrafts]=useState<Drafts>(); const [selectedDrafts,setSelectedDrafts]=useState<string[]>([]); const [running,setRunning]=useState(false); const [loading,setLoading]=useState(false); const [form]=Form.useForm();
 const capabilityMap=useMemo(()=>new Map(capabilities.map(item=>[item.key,item])),[capabilities]);
 const capabilityLabel=(key:string)=>{const item=capabilityMap.get(key);return item?t(item.name_i18n_key):key};
 const load=async()=>{if(!localAvailable)return;setLoading(true);try{setPresets(await listLearningPresets("document",documentId))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[documentId,localAvailable]);
 useEffect(()=>setSelected(capabilities.map(x=>x.key)),[capabilities]);
 const counts=useMemo(()=>presets.reduce<Record<string,number>>((out,row)=>{out[row.capability_key]=(out[row.capability_key]||0)+1;return out},{}),[presets]);
 const visible=filter==="all"?presets:presets.filter(row=>row.capability_key===filter);
 const openCreate=()=>{form.resetFields();form.setFieldsValue({capability_key:capabilities[0]?.key});setEditor({open:true})};
 const openEdit=(preset:LearningPreset)=>{form.setFieldsValue({capability_key:preset.capability_key,key:preset.normalized_key,...parseValue(preset.value_json)});setEditor({open:true,preset})};
 const save=async()=>{const values=await form.validateFields();const capability=capabilityMap.get(values.capability_key);if(!capability)return;const content=Object.fromEntries(capability.fields.map(field=>[field.key,values[field.key]]).filter(([,value])=>value!==undefined&&value!==""));if(editor.preset)await updateLearningPreset(editor.preset.id,content,editor.preset.priority);else await putLearningPreset({scope_type:"document",scope_id:documentId,document_revision:revision||"",capability_key:values.capability_key,key:values.key,value:content,origin:"user"});message.success(t("common.saveSuccess"));setEditor({open:false});await load()};
 const remove=async(id:string)=>{await deleteLearningPreset(id);message.success(t("common.success"));await load()};
 const analyze=async()=>{setRunning(true);try{const created=await createPreanalysisTask({dataset_id:datasetId,document_id:documentId,document_revision:revision,capability_keys:selected});setTask(created);await runPreanalysisTask(created.id);let result=created;while(["queued","running"].includes(result.status)){await new Promise(resolve=>window.setTimeout(resolve,750));result=await getPreanalysisTask(created.id);setTask(result)}if(result.status==="failed")throw new Error(t("learning.preanalysisFailed"));const next=await listPreanalysisDrafts(result.id);setDrafts(next);setSelectedDrafts(next.presets.map(x=>x.id));message.success(t("learning.preanalysisFinished"))}catch(e){message.error(e instanceof Error?e.message:String(e))}finally{setRunning(false)}};
 const publish=async()=>{if(!task||!drafts)return;await publishPreanalysisDrafts(task.id,revision||"",selectedDrafts,[]);setDrafts(undefined);message.success(t("learning.preanalysisPublished"));await load()};
 const editingCapability=capabilityMap.get(Form.useWatch("capability_key",form));
 return <div className="document-analysis">
  {!localAvailable?<Alert type="warning" showIcon message={t("vocabulary.localOnlyDesktop")}/>:null}
  <div className="document-analysis__header"><div><Typography.Title level={4}>{t("learning.presetAnswers")}</Typography.Title><Typography.Text type="secondary">{t("learning.presetAnswersHint")}</Typography.Text></div><Space><Button icon={<RobotOutlined/>} disabled={!localAvailable} onClick={()=>setDrafts({presets:[],contents:[]})}>{t("learning.aiGenerate")}</Button><Button type="primary" icon={<PlusOutlined/>} disabled={!localAvailable} onClick={openCreate}>{t("learning.addPresetAnswer")}</Button></Space></div>
  <Segmented className="document-analysis__filters" value={filter} onChange={value=>setFilter(String(value))} options={[{value:"all",label:`${t("common.all")} ${presets.length}`},...capabilities.filter(item=>counts[item.key]).map(item=>({value:item.key,label:`${t(item.name_i18n_key)} ${counts[item.key]}`}))]}/>
  <Spin spinning={loading}><List className="document-analysis__list" dataSource={visible} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t("learning.noPresetAnswers")}/>}} renderItem={item=><List.Item actions={[<Button key="edit" type="text" icon={<EditOutlined/>} aria-label={t("common.edit")} onClick={()=>openEdit(item)}/>,<Popconfirm key="delete" title={t("learning.deletePresetConfirm")} onConfirm={()=>void remove(item.id)}><Button type="text" danger icon={<DeleteOutlined/>} aria-label={t("common.delete")}/></Popconfirm>]}><List.Item.Meta title={<Space><Typography.Text strong>{item.normalized_key}</Typography.Text><Tag>{capabilityLabel(item.capability_key)}</Tag></Space>} description={<><Typography.Paragraph ellipsis={{rows:2}}>{valueSummary(item.value_json)}</Typography.Paragraph><Typography.Text type="secondary" className="document-analysis__origin">{item.origin==="user"?t("learning.manuallyAdded"):t("learning.aiGenerated")}</Typography.Text></>}/></List.Item>}/></Spin>
  <Modal open={editor.open} title={editor.preset?t("learning.editPresetAnswer"):t("learning.addPresetAnswer")} onCancel={()=>setEditor({open:false})} onOk={()=>void save()} okText={t("common.save")} destroyOnHidden><Form form={form} layout="vertical"><Form.Item name="capability_key" label={t("learning.answerType")} rules={[{required:true}]}><Select disabled={!!editor.preset} options={capabilities.map(item=>({value:item.key,label:t(item.name_i18n_key)}))}/></Form.Item><Form.Item name="key" label={t("learning.matchContent")} extra={t("learning.matchContentHint")} rules={[{required:true}]}><Input disabled={!!editor.preset}/></Form.Item>{editingCapability?.fields.map(field=><Form.Item key={field.key} name={field.key} label={t(field.label_i18n_key)} rules={field.required?[{required:true,message:t("learning.requiredField")}]:undefined}>{field.type==="string_list"?<Select mode="tags" tokenSeparators={[",","，"]}/>:field.type==="text"?<Input.TextArea rows={4}/>:<Input/>}</Form.Item>)}</Form></Modal>
  <Modal open={!!drafts} title={t("learning.aiAnalysisTitle")} width={720} onCancel={()=>!running&&setDrafts(undefined)} footer={drafts?.presets.length?[<Button key="cancel" onClick={()=>setDrafts(undefined)}>{t("common.cancel")}</Button>,<Button key="publish" type="primary" disabled={!selectedDrafts.length} onClick={()=>void publish()}>{t("learning.addSelected",{count:selectedDrafts.length})}</Button>]:null}>
   {!drafts?.presets.length?<div className="document-analysis__generator"><RobotOutlined/><Typography.Title level={5}>{t("learning.chooseAnalysisCapabilities")}</Typography.Title><Typography.Text type="secondary">{t("learning.chooseAnalysisCapabilitiesHint")}</Typography.Text><Select mode="multiple" value={selected} onChange={setSelected} options={capabilities.map(x=>({value:x.key,label:t(x.name_i18n_key)}))}/><Button type="primary" loading={running} disabled={!selected.length} onClick={()=>void analyze()}>{t("learning.startAnalysis")}</Button>{task?<Typography.Text type="secondary">{t("learning.preanalysisStatus",{status:task.status,completed:task.completed,failed:task.failed})}</Typography.Text>:null}</div>:<><Typography.Paragraph>{t("learning.aiCandidatesFound",{count:drafts.presets.length})}</Typography.Paragraph><Checkbox indeterminate={selectedDrafts.length>0&&selectedDrafts.length<drafts.presets.length} checked={selectedDrafts.length===drafts.presets.length} onChange={event=>setSelectedDrafts(event.target.checked?drafts.presets.map(x=>x.id):[])}>{t("common.selectAll")}</Checkbox><List className="document-analysis__drafts" dataSource={drafts.presets} renderItem={item=><List.Item><Checkbox checked={selectedDrafts.includes(item.id)} onChange={event=>setSelectedDrafts(current=>event.target.checked?[...current,item.id]:current.filter(id=>id!==item.id))}><Typography.Text strong>{item.normalized_key}</Typography.Text><Tag>{capabilityLabel(item.capability_key)}</Tag><Typography.Paragraph ellipsis={{rows:2}}>{valueSummary(item.value_json)}</Typography.Paragraph></Checkbox></List.Item>}/></>}
  </Modal>
 </div>
}
