import { Alert, Button, Card, Form, Input, List, Select, Space, Typography, message } from "antd";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { createPreanalysisTask, getPreanalysisTask, listPreanalysisDrafts, publishPreanalysisDrafts, putLearningPreset, runPreanalysisTask, type LearningCapability } from "./api";

export default function DocumentLearningPanel({datasetId,documentId,revision,capabilities,localAvailable}:{datasetId:string;documentId:string;revision?:string;capabilities:LearningCapability[];localAvailable:boolean}){
 const {t}=useTranslation();const [selected,setSelected]=useState<string[]>(capabilities.map(x=>x.key));const [task,setTask]=useState<{id:string;status:string;total:number;completed:number;failed:number;result_json:string}>();const [drafts,setDrafts]=useState<{presets:Array<{id:string;capability_key:string;normalized_key:string;value_json:string}>;contents:Array<{id:string;capability_key:string;content_json:string}>}>();const [running,setRunning]=useState(false);const [form]=Form.useForm();
 const analyze=async()=>{setRunning(true);try{const created=await createPreanalysisTask({dataset_id:datasetId,document_id:documentId,document_revision:revision,capability_keys:selected});setTask(created);await runPreanalysisTask(created.id);let result=created;while(["queued","running"].includes(result.status)){await new Promise(resolve=>window.setTimeout(resolve,750));result=await getPreanalysisTask(created.id);setTask(result)}if(result.status==="failed")throw new Error(t("learning.preanalysisFailed"));setDrafts(await listPreanalysisDrafts(result.id));message.success(t("learning.preanalysisFinished"))}catch(e){message.error(e instanceof Error?e.message:String(e))}finally{setRunning(false)}};
 const publish=async()=>{if(!task||!drafts)return;await publishPreanalysisDrafts(task.id,revision||"",drafts.presets.map(x=>x.id),drafts.contents.map(x=>x.id));setDrafts({presets:[],contents:[]});message.success(t("learning.preanalysisPublished"))};
 const savePreset=async()=>{const value=await form.validateFields();let parsed:Record<string,unknown>;try{parsed=JSON.parse(value.value_json)}catch{message.error(t("learning.invalidJson"));return}await putLearningPreset({scope_type:value.scope_type,scope_id:value.scope_type==="document"?documentId:value.scope_type==="knowledge_base"?datasetId:"",document_revision:revision||"",capability_key:value.capability_key,key:value.key,value:parsed,origin:"user"});message.success(t("common.saveSuccess"));form.resetFields(["key","value_json"])};
 return <Space direction="vertical" style={{width:"100%"}} size={16}>{!localAvailable?<Alert type="warning" showIcon message={t("vocabulary.localOnlyDesktop")}/>:null}<Card title={t("learning.preanalysis")}><Space direction="vertical" style={{width:"100%"}}><Select mode="multiple" value={selected} onChange={setSelected} options={capabilities.map(x=>({value:x.key,label:t(x.name_i18n_key)}))}/><Button type="primary" loading={running} disabled={!localAvailable||selected.length===0} onClick={()=>void analyze()}>{t("learning.analyzeDocument")}</Button>{task?<Typography.Text>{t("learning.preanalysisStatus",{status:task.status,completed:task.completed,failed:task.failed})}</Typography.Text>:null}{drafts&&drafts.presets.length+drafts.contents.length>0?<><List size="small" header={t("learning.preanalysisDrafts")} dataSource={drafts.presets.map(x=>({id:x.id,label:`${x.capability_key}: ${x.normalized_key}`}))} renderItem={item=><List.Item>{item.label}</List.Item>}/><Button type="primary" onClick={()=>void publish()}>{t("learning.publishDrafts")}</Button></>:null}</Space></Card><Card title={t("learning.presetContent")}><Form form={form} layout="vertical" initialValues={{scope_type:"document"}}><Form.Item name="scope_type" label={t("learning.cacheScope")}><Select options={[{value:"user_global",label:t("learning.scopeGlobal")},{value:"knowledge_base",label:t("learning.scopeKnowledgeBase")},{value:"document",label:t("learning.scopeDocument")} ]}/></Form.Item><Form.Item name="capability_key" label={t("vocabulary.capabilityLabel")} rules={[{required:true}]}><Select options={capabilities.map(x=>({value:x.key,label:t(x.name_i18n_key)}))}/></Form.Item><Form.Item name="key" label={t("learning.presetKey")} rules={[{required:true}]}><Input/></Form.Item><Form.Item name="value_json" label={t("learning.presetValue")} rules={[{required:true}]}><Input.TextArea rows={6} placeholder='{"translation":"..."}'/></Form.Item><Button onClick={()=>void savePreset()} disabled={!localAvailable}>{t("common.save")}</Button></Form></Card></Space>
}
