import { Alert, Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Table, Typography, message } from "antd";
import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { answerLearningQuestion, archiveLearningBook, createLearningBook, createLearningReviewSession, getLearningCatalog, importLearningDictionary, listLearningBooks, updateLearningBook, type LearningBook, type LearningCatalog } from "./api";

type SessionItem={question:{id:string;question_type:string;payload_json:string};card:{id:string;question_type:string}};
type SessionView={session:{id:string;total:number;answered:number;status:string};items:SessionItem[]};
const supported=new Set(["single_choice","text_input","cloze","true_false","translation_response","short_answer","rubric_self_assessment"]);

export default function LearningCollectionsPanel({localAvailable}:{localAvailable:boolean}){
 const {t,i18n}=useTranslation();const [catalog,setCatalog]=useState<LearningCatalog>();const [books,setBooks]=useState<LearningBook[]>([]);const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<LearningBook>();const [importing,setImporting]=useState(false);const [form]=Form.useForm();const [importForm]=Form.useForm();const [session,setSession]=useState<SessionView>();const [index,setIndex]=useState(0);const [response,setResponse]=useState("");
 const load=()=>Promise.all([getLearningCatalog(),listLearningBooks()]).then(([c,b])=>{setCatalog(c);setBooks(b)});useEffect(()=>{void load()},[]);
 const selectedCapability=Form.useWatch("capability_key",form);const capability=useMemo(()=>catalog?.capabilities.find(x=>x.key===selectedCapability),[catalog,selectedCapability]);
 const questionLabel=(key:string)=>{const d=catalog?.question_types.find(x=>x.key===key);return d?t(d.name_i18n_key):key};
 const save=async()=>{const value=await form.validateFields();if(editing){await updateLearningBook(editing.id,value)}else{await createLearningBook(value)}message.success(t(editing?"learning.collectionUpdated":"learning.collectionCreated"));setCreating(false);setEditing(undefined);form.resetFields();await load()};
 const edit=(book:LearningBook)=>{setEditing(book);setCreating(true);form.setFieldsValue({name:book.name,description:book.description,capability_key:book.capability_key,question_types:JSON.parse(book.question_types_json)})};
 const archive=async(id:string)=>{await archiveLearningBook(id);message.success(t("learning.collectionArchived"));await load()};
 const start=async(book:LearningBook)=>{try{const value=await createLearningReviewSession(book.id,i18n.language);setSession(value);setIndex(0);setResponse("")}catch(e){message.info(e instanceof Error?e.message:String(e))}};
 const item=session?.items[index];let payload:Record<string,unknown>={};try{payload=item?JSON.parse(item.question.payload_json):{}}catch{/* invalid payload is handled below */}
 const submit=async(rating?:string)=>{if(!session||!item)return;await answerLearningQuestion(session.session.id,{question_id:item.question.id,response,rating,idempotency_key:crypto.randomUUID()});if(index+1>=session.items.length){message.success(t("learning.reviewCompleted"));setSession(undefined)}else{setIndex(index+1);setResponse("")}};
 const importDictionary=async()=>{const value=await importForm.validateFields();let entries:unknown;try{entries=JSON.parse(value.entries_json)}catch{message.error(t("learning.invalidJson"));return}const result=await importLearningDictionary({...value,entries});message.success(t("learning.dictionaryImported",{count:result.imported}));setImporting(false);importForm.resetFields()};
 return <Space direction="vertical" style={{width:"100%"}} size={16}>
  {!localAvailable?<Alert type="warning" showIcon message={t("vocabulary.localOnlyDesktop")}/>:null}
  <Space style={{justifyContent:"space-between",width:"100%"}}><Typography.Title level={4}>{t("learning.learningCollections")}</Typography.Title><Space><Button disabled={!localAvailable} onClick={()=>setImporting(true)}>{t("learning.importDictionary")}</Button><Button type="primary" disabled={!localAvailable} onClick={()=>setCreating(true)}>{t("learning.createCollection")}</Button></Space></Space>
  <Table rowKey="id" dataSource={books} pagination={false} columns={[{title:t("learning.collectionName"),dataIndex:"name"},{title:t("vocabulary.capabilityLabel"),dataIndex:"capability_key",render:(key:string)=>{const d=catalog?.capabilities.find(x=>x.key===key);return d?t(d.name_i18n_key):key}},{title:t("vocabulary.questionTypesLabel"),dataIndex:"question_types_json",render:(raw:string)=>{try{return (JSON.parse(raw) as string[]).map(questionLabel).join("、")}catch{return raw}}},{title:t("common.action"),render:(_:unknown,row:LearningBook)=><Space><Button onClick={()=>void start(row)} disabled={!localAvailable}>{t("learning.startReview")}</Button><Button onClick={()=>edit(row)} disabled={!localAvailable}>{t("common.edit")}</Button><Popconfirm title={t("learning.archiveCollectionConfirm")} onConfirm={()=>void archive(row.id)}><Button danger disabled={!localAvailable}>{t("common.delete")}</Button></Popconfirm></Space>}]}/>
  <Modal open={creating} title={t(editing?"learning.editCollection":"learning.createCollection")} onCancel={()=>{setCreating(false);setEditing(undefined);form.resetFields()}} onOk={()=>void save()}><Form form={form} layout="vertical"><Form.Item name="name" label={t("learning.collectionName")} rules={[{required:true}]}><Input/></Form.Item><Form.Item name="description" label={t("knowledge.knowledgeDesc")}><Input.TextArea/></Form.Item><Form.Item name="capability_key" label={t("vocabulary.capabilityLabel")} rules={[{required:true}]}><Select disabled={!!editing} options={catalog?.capabilities.map(x=>({value:x.key,label:t(x.name_i18n_key),disabled:x.local_only&&!localAvailable}))} onChange={key=>{const d=catalog?.capabilities.find(x=>x.key===key);form.setFieldValue("question_types",d?.default_question_types||[])}}/></Form.Item><Form.Item name="question_types" label={t("vocabulary.questionTypesLabel")} rules={[{required:true}]}><Select mode="multiple" options={capability?.allowed_question_types.map(key=>({value:key,label:questionLabel(key)}))}/></Form.Item></Form></Modal>
  <Modal open={importing} title={t("learning.importDictionary")} onCancel={()=>setImporting(false)} onOk={()=>void importDictionary()}><Form form={importForm} layout="vertical"><Form.Item name="provider_key" label={t("learning.dictionaryType")} rules={[{required:true}]}><Select options={[{value:"chinese_dictionary",label:t("learning.chineseDictionary")},{value:"chinese_idiom_dictionary",label:t("learning.idiomDictionary")},{value:"classical_chinese_dictionary",label:t("learning.classicalDictionary")} ]}/></Form.Item>{[["source_name",t("learning.sourceName")],["source_version",t("learning.sourceVersion")],["license_id",t("learning.license")],["checksum",t("learning.checksum")]].map(([name,label])=><Form.Item key={name} name={name} label={label} rules={[{required:true}]}><Input/></Form.Item>)}<Form.Item name="source_url" label={t("learning.sourceUrl")}><Input/></Form.Item><Form.Item name="entries_json" label={t("learning.dictionaryEntriesJson")} rules={[{required:true}]}><Input.TextArea rows={7}/></Form.Item></Form></Modal>
  <Modal open={!!session} title={t("learning.reviewProgress",{current:index+1,total:session?.items.length||0})} footer={null} onCancel={()=>setSession(undefined)}>{item?!supported.has(item.question.question_type)?<Alert type="error" message={t("learning.unsupportedQuestionType",{type:item.question.question_type})}/>:<Card><Typography.Paragraph strong>{String(payload.prompt||"")}</Typography.Paragraph>{item.question.question_type==="single_choice"?<Select style={{width:"100%"}} options={Array.isArray(payload.options)?payload.options.map(x=>({value:String(x),label:String(x)})):[]} value={response||undefined} onChange={setResponse}/>:item.question.question_type==="true_false"?<Select style={{width:"100%"}} options={[{value:"true",label:t("common.yes")},{value:"false",label:t("common.no")}]} onChange={setResponse}/>:item.question.question_type==="rubric_self_assessment"?<Space><Button onClick={()=>void submit("again")}>{t("learning.rating.again")}</Button><Button onClick={()=>void submit("hard")}>{t("learning.rating.hard")}</Button><Button onClick={()=>void submit("good")}>{t("learning.rating.good")}</Button><Button onClick={()=>void submit("easy")}>{t("learning.rating.easy")}</Button></Space>:<Input.TextArea value={response} onChange={e=>setResponse(e.target.value)} rows={4}/>} {item.question.question_type!=="rubric_self_assessment"?<Button type="primary" style={{marginTop:12}} onClick={()=>void submit()}>{t("learning.submitAnswer")}</Button>:null}</Card>:null}</Modal>
 </Space>
}
