import { describe, expect, it } from "vitest";
import {
  createEmptyModel,
  expressionMaterials,
  formatExpression,
  isHiddenId,
  newHiddenId,
  removeMaterialFromExpression,
  type MaterialExpression,
} from "./model";

describe("createEmptyModel", () => {
  it("returns an empty graph model with all collections initialized", () => {
    const model = createEmptyModel();

    expect(model).toEqual({
      nodes: [],
      slots: {},
      layout: {},
      edgeLayout: {},
      startTransitions: [],
      startRoute: undefined,
    });
  });
});

describe("isHiddenId / newHiddenId", () => {
  it("recognizes ids generated by newHiddenId as hidden", () => {
    const id = newHiddenId();

    expect(isHiddenId(id)).toBe(true);
    expect(id.startsWith(".hid-")).toBe(true);
  });

  it("treats user-assigned ids as not hidden", () => {
    expect(isHiddenId("write_outline")).toBe(false);
  });
});

describe("expressionMaterials", () => {
  it("returns an empty array when no expression is provided", () => {
    expect(expressionMaterials(undefined)).toEqual([]);
  });

  it("collects the single material from a leaf expression", () => {
    expect(expressionMaterials({ material: "outline" })).toEqual(["outline"]);
  });

  it("collects unique materials from nested all/any expressions", () => {
    const expr: MaterialExpression = {
      all: [
        { material: "outline" },
        { any: [{ material: "draft" }, { material: "outline" }] },
      ],
    };

    expect(expressionMaterials(expr)).toEqual(["outline", "draft"]);
  });
});

describe("removeMaterialFromExpression", () => {
  it("returns undefined when removing the only material from a leaf expression", () => {
    expect(removeMaterialFromExpression({ material: "outline" }, "outline")).toBeUndefined();
  });

  it("leaves a non-matching leaf expression untouched", () => {
    const expr: MaterialExpression = { material: "outline" };
    expect(removeMaterialFromExpression(expr, "draft")).toBe(expr);
  });

  it("collapses an all/any group down to a single child when one is removed", () => {
    const expr: MaterialExpression = {
      all: [{ material: "outline" }, { material: "draft" }],
    };

    const result = removeMaterialFromExpression(expr, "draft");
    expect(result).toEqual({ material: "outline" });
  });

  it("removes the whole group once every child material is removed", () => {
    const expr: MaterialExpression = { any: [{ material: "outline" }] };
    expect(removeMaterialFromExpression(expr, "outline")).toBeUndefined();
  });
});

describe("formatExpression", () => {
  it("returns an empty string for an undefined expression", () => {
    expect(formatExpression(undefined)).toBe("");
  });

  it("formats a leaf expression as the bare material id", () => {
    expect(formatExpression({ material: "outline" })).toBe("outline");
  });

  it("formats an all-group with AND and parentheses", () => {
    const expr: MaterialExpression = { all: [{ material: "outline" }, { material: "draft" }] };
    expect(formatExpression(expr)).toBe("(outline AND draft)");
  });

  it("formats an any-group with OR and parentheses", () => {
    const expr: MaterialExpression = { any: [{ material: "outline" }, { material: "draft" }] };
    expect(formatExpression(expr)).toBe("(outline OR draft)");
  });
});
