import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { MemoryRouter } from 'react-router-dom';
import { Modal } from 'antd';
import { TerminalConnectionPage } from '@/modules/channelGateway';
const mocks = vi.hoisted(() => ({ accounts: vi.fn(), create: vi.fn(), detail: vi.fn(), refs: vi.fn(), disconnect: vi.fn(), cancel: vi.fn() }));
vi.mock('@/modules/channelGateway/api', async importOriginal => ({ ...await importOriginal<typeof import('@/modules/channelGateway/api')>(), listChannelAccounts: mocks.accounts, createConnectionSession: mocks.create, disconnectChannelAccount: mocks.disconnect, cancelConnectionSession: mocks.cancel }));
vi.mock('./api', async importOriginal => ({ ...await importOriginal<typeof import('./api')>(), getAccountDetail: mocks.detail, getReferences: mocks.refs }));
vi.mock('react-i18next', async importOriginal => { const t = (key: string) => key; return { ...await importOriginal<typeof import('react-i18next')>(), useTranslation: () => ({ t }) }; });
beforeEach(() => { vi.clearAllMocks(); mocks.accounts.mockResolvedValue({ items: [] }); mocks.cancel.mockResolvedValue(undefined); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
describe('channel connection workspace', () => {
  it('uses credentials for WeCom and clears the secret after submission', async () => {
    mocks.create.mockResolvedValue({ id: 'session', provider: 'wecom', mode: 'credentials', status: 'connected', allowed_actions: [] });
    render(<MemoryRouter><TerminalConnectionPage initialProvider="wecom" /></MemoryRouter>);
    expect(screen.queryByRole('button', { name: /startScan/ })).not.toBeInTheDocument();
    fireEvent.change(screen.getByLabelText('BotID'), { target: { value: 'test-bot' } });
    fireEvent.change(screen.getByLabelText('Secret'), { target: { value: 'fixture-secret' } });
    fireEvent.click(screen.getByRole('button', { name: 'notifications.connectAction' }));
    await waitFor(() => expect(mocks.create).toHaveBeenCalledWith('wecom', expect.objectContaining({ credentials: { bot_id: 'test-bot', secret: 'fixture-secret' }, idempotencyKey: expect.any(String) })));
    await waitFor(() => expect(screen.getByLabelText('Secret')).toHaveValue(''));
    expect(JSON.stringify(localStorage)).not.toContain('fixture-secret');
  });
  it('blocks disconnect when reference lookup fails and reconnects with the original account ID', async () => {
    const account = { id: 'original', provider: 'wecom', label: 'Work account', status: 'connected', runtime_status: 'running', updated_at: '2026-09-17' };
    mocks.accounts.mockImplementation((p: string) => Promise.resolve({ items: p === 'wecom' ? [account] : [] }));
    mocks.detail.mockResolvedValue({ ...account, primary_recipient: null, notification_reference_count: 1 });
    mocks.refs.mockRejectedValue(new Error('unavailable'));
    const confirm = vi.spyOn(Modal, 'confirm');
    const view = render(<MemoryRouter><TerminalConnectionPage initialProvider="wecom" /></MemoryRouter>);
    await screen.findByText('Work account');
    const disclosure = document.querySelector('details')!;
    disclosure.open = true; fireEvent(disclosure, new Event('toggle'));
    fireEvent.click(await screen.findByRole('button', { name: 'notifications.disconnect' }));
    await screen.findByText('notifications.loadFailed');
    expect(mocks.disconnect).not.toHaveBeenCalled(); expect(confirm).not.toHaveBeenCalled();
    view.unmount();
    account.status = 'disconnected';
    mocks.create.mockResolvedValue({ id: 's', provider: 'wecom', mode: 'credentials', status: 'connected', allowed_actions: [] });
    render(<MemoryRouter><TerminalConnectionPage initialProvider="wecom" /></MemoryRouter>);
    await screen.findByText('Work account');
    const disconnected = document.querySelector('details')!; disconnected.open = true; fireEvent(disconnected, new Event('toggle'));
    fireEvent.click(await screen.findByRole('button', { name: 'notifications.reconnect' }));
    fireEvent.change(screen.getByLabelText('BotID'), { target: { value: 'test-bot' } });
    fireEvent.change(screen.getByLabelText('Secret'), { target: { value: 'test-secret' } });
    fireEvent.click(screen.getByRole('button', { name: 'notifications.connectAction' }));
    await waitFor(() => expect(mocks.create).toHaveBeenCalledWith('wecom', expect.objectContaining({ accountId: 'original' })));
  });
});
