package main

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

const fixtureDesktopIdentity = `{"version":1,"deviceId":"11111111-2222-4333-8444-555555555555","deviceSecret":"AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8"}`

// This vector was generated by the existing Desktop HMAC formula in Node.
const fixtureDesktopCloudKey = "h7WpwdOhjknp0SaBxDAy0KTFhe6hV9TYvOnyUkm08P0"

func fixtureCredentialDevicePath(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	t.Setenv(localHostHomeEnvVar, home)
	t.Setenv("LOCALAPPDATA", filepath.Join(home, "AppData", "Local"))
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(home, ".config"))
	switch runtime.GOOS {
	case "darwin":
		return filepath.Join(home, "Library", "Application Support", "lazymind-desktop", "credential-device.json")
	case "windows":
		return filepath.Join(home, "AppData", "Local", "LazyMind", "Desktop", "credential-device.json")
	default:
		return filepath.Join(home, ".config", "lazymind-desktop", "credential-device.json")
	}
}

func TestLocalAuthServiceUsesExistingDesktopCredentialKey(t *testing.T) {
	identityPath := fixtureCredentialDevicePath(t)
	if err := os.MkdirAll(filepath.Dir(identityPath), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(identityPath, []byte(fixtureDesktopIdentity), 0o600); err != nil {
		t.Fatal(err)
	}
	// Existing local/config.env exports this legacy value even after an upgrade.
	t.Setenv("LAZYMIND_AUTH_CLOUD_SECRET_KEY", "dev-ragscan-secret-key-change-me")
	env := mustAuthServiceEnv(t, RuntimeConfig{Profile: "local"}, RuntimePaths{})
	for _, value := range env {
		if strings.HasPrefix(value, "LAZYMIND_AUTH_CLOUD_SECRET_KEY=") {
			if strings.TrimPrefix(value, "LAZYMIND_AUTH_CLOUD_SECRET_KEY=") != fixtureDesktopCloudKey {
				t.Fatal("Local auth-service cannot read credentials encrypted by the existing Desktop device key")
			}
			return
		}
	}
	t.Fatal("auth-service encryption key is missing")
}

func mustAuthServiceEnv(t *testing.T, cfg RuntimeConfig, paths RuntimePaths) []string {
	t.Helper()
	env, err := authServiceEnv(cfg, paths)
	if err != nil {
		t.Fatal(err)
	}
	return env
}

func authCloudKeyForTest(t *testing.T, profile string) string {
	t.Helper()
	for _, value := range mustAuthServiceEnv(t, RuntimeConfig{Profile: profile}, RuntimePaths{}) {
		if key, value, ok := strings.Cut(value, "="); ok && key == cloudCredentialKeyEnvVar {
			return value
		}
	}
	t.Fatal("auth-service encryption key is missing")
	return ""
}

func writeCredentialIdentityFixture(t *testing.T, path, body string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

func desktopCloudKeyForTest(t *testing.T, identityPath string, configured ...string) string {
	t.Helper()
	node, err := exec.LookPath("node")
	if err != nil {
		t.Fatal("Node is required to verify the existing Desktop identity contract")
	}
	mainPath, err := filepath.Abs(filepath.Join("..", "..", "desktop", "electron", "src", "main.js"))
	if err != nil {
		t.Fatal(err)
	}
	// Execute the original Desktop identity loader and derivation, without Electron.
	script := `
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const vm = require('node:vm');
const source = fs.readFileSync(process.argv[2], 'utf8');
const start = source.indexOf('function loadOrCreateDesktopCredentialIdentity()');
const marker = 'const desktopCredentialIdentity = loadOrCreateDesktopCredentialIdentity();';
const end = source.indexOf(marker, start) + marker.length;
if (start < 0 || end < marker.length) throw new Error('Desktop identity implementation missing');
const context = vm.createContext({ fs, path, Buffer, ...crypto, desktopCredentialIdentityPath: process.argv[1] });
vm.runInContext(source.slice(start, end), context);
if (process.argv[3] === undefined) {
  process.stdout.write(vm.runInContext("deriveDesktopCredentialKey(desktopCredentialIdentity, 'cloud-oauth')", context));
} else {
  Object.assign(context, {
    process: { env: process.argv[3] ? { LAZYMIND_AUTH_CLOUD_SECRET_KEY: process.argv[3] } : {}, pid: 1, execPath: 'fixture-node' },
    loadAccessState: () => ({ allowedRoots: [] }),
    loadObsidianConfig: () => ({ root: '' }),
    buildObsidianRuntimeEnv: () => ({}),
    localFolderAccessStatePath: '', obsidianConfigPath: '', obsidianDisabledRoot: '',
    ownerToken: 'fixture-owner', internalServiceToken: 'fixture-token', clientInstanceId: 'fixture-instance',
    cloudBaseURL: '', app: { getVersion: () => 'fixture-version' }, runtimeResourcesRoot: '',
    editablePptDependencyConfig: { windowsX64: {}, darwinArm64: {} }, explicitRuntimeRoot: '',
  });
  const envStart = source.indexOf('function sidecarEnv()');
  const envEnd = source.indexOf('function sidecarShutdownEnv()', envStart);
  vm.runInContext(source.slice(envStart, envEnd), context);
  const env = vm.runInContext('sidecarEnv()', context);
  if (!env.LAZYMIND_MODEL_PROVIDER_SECRET_KEY || !env.LAZYMIND_MCP_SECRET_KEY) {
    throw new Error('Desktop model/MCP key injection changed');
  }
  process.stdout.write(env.LAZYMIND_AUTH_CLOUD_SECRET_KEY || '');
}
`
	args := append([]string{"-e", script, identityPath, mainPath}, configured...)
	output, err := exec.Command(node, args...).Output()
	if err != nil {
		t.Fatalf("execute Desktop identity contract: %v", err)
	}
	return string(output)
}

func TestDesktopAuthServiceUsesSharedCredentialSelection(t *testing.T) {
	for _, configured := range []string{"", "dev-ragscan-secret-key-change-me", "fixture-custom-key"} {
		path := fixtureCredentialDevicePath(t)
		writeCredentialIdentityFixture(t, path, fixtureDesktopIdentity)
		t.Setenv(cloudCredentialKeyEnvVar, desktopCloudKeyForTest(t, path, configured))
		want := fixtureDesktopCloudKey
		if configured == "fixture-custom-key" {
			want = configured
		}
		if authCloudKeyForTest(t, "desktop") != want {
			t.Fatal("Desktop sidecar environment bypasses the shared cloud key selection")
		}
	}
	path := fixtureCredentialDevicePath(t)
	broken := strings.Replace(fixtureDesktopIdentity, "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8", "invalid-secret", 1)
	writeCredentialIdentityFixture(t, path, broken)
	// The original Desktop loader accepts this shape; its automatic cloud key
	// must not be mistaken for an explicit override at the shared Go boundary.
	t.Setenv(cloudCredentialKeyEnvVar, desktopCloudKeyForTest(t, path, ""))
	if _, err := authServiceEnv(RuntimeConfig{Profile: "desktop"}, RuntimePaths{}); err == nil {
		t.Fatal("Desktop automatic key bypassed invalid identity validation")
	}
	raw, err := os.ReadFile(path)
	if err != nil || string(raw) != broken {
		t.Fatal("invalid Desktop identity was replaced")
	}
}

func TestCloudCredentialKeyConfigurationAndProfileSwitching(t *testing.T) {
	for _, configured := range []string{"", "dev-ragscan-secret-key-change-me", "  dev-ragscan-secret-key-change-me  ", " fixture-custom-key "} {
		t.Run(configured, func(t *testing.T) {
			path := fixtureCredentialDevicePath(t)
			writeCredentialIdentityFixture(t, path, fixtureDesktopIdentity)
			t.Setenv(cloudCredentialKeyEnvVar, configured)
			want := fixtureDesktopCloudKey
			if strings.TrimSpace(configured) == "fixture-custom-key" {
				want = "fixture-custom-key"
			}
			for _, profile := range []string{"local", "desktop", "local"} {
				if authCloudKeyForTest(t, profile) != want {
					t.Fatal("profile switching changed the auth-service encryption key")
				}
			}
			raw, err := os.ReadFile(path)
			if err != nil || string(raw) != fixtureDesktopIdentity {
				t.Fatal("existing Desktop identity was changed")
			}
			if desktopCloudKeyForTest(t, path) != fixtureDesktopCloudKey {
				t.Fatal("fixture is incompatible with the existing Desktop key derivation")
			}
		})
	}
}

func TestCloudCredentialIdentityCanBeCreatedByEitherMode(t *testing.T) {
	for _, first := range []string{"local", "desktop"} {
		t.Run(first, func(t *testing.T) {
			path := fixtureCredentialDevicePath(t)
			t.Setenv(cloudCredentialKeyEnvVar, "")
			var key string
			if first == "desktop" {
				key = desktopCloudKeyForTest(t, path)
			} else {
				key = authCloudKeyForTest(t, "local")
			}
			raw, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			for _, profile := range []string{"local", "desktop", "local"} {
				if authCloudKeyForTest(t, profile) != key {
					t.Fatal("restart or mode switch rotated the device key")
				}
			}
			if desktopCloudKeyForTest(t, path) != key {
				t.Fatal("Local-created identity is incompatible with Desktop")
			}
			after, err := os.ReadFile(path)
			if err != nil || string(after) != string(raw) {
				t.Fatal("identity changed after another mode read it")
			}
			info, err := os.Stat(path)
			if err != nil {
				t.Fatal(err)
			}
			if runtime.GOOS != "windows" && info.Mode().Perm() != 0o600 {
				t.Fatal("new identity is not restricted to its owner")
			}
		})
	}
}

func TestCloudCredentialIdentityFailuresDoNotOverwriteOrStartService(t *testing.T) {
	for _, body := range []string{
		"invalid-json", "{}",
		strings.Replace(fixtureDesktopIdentity, `"version":1`, `"version":2`, 1),
		strings.Replace(fixtureDesktopIdentity, `"11111111-2222-4333-8444-555555555555"`, `""`, 1),
		strings.Replace(fixtureDesktopIdentity, "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8", "invalid-secret", 1),
	} {
		path := fixtureCredentialDevicePath(t)
		writeCredentialIdentityFixture(t, path, body)
		t.Setenv(cloudCredentialKeyEnvVar, "")
		runner := &fakeRunner{t: t}
		err := NewAuthServiceManager(runner).Run(context.Background(), RuntimeConfig{}, RuntimePaths{})
		if err == nil || !strings.Contains(err.Error(), "invalid credential device identity") {
			t.Fatal("invalid identity did not stop auth-service startup")
		}
		runner.assertCommandCount(0)
		raw, readErr := os.ReadFile(path)
		if readErr != nil || string(raw) != body {
			t.Fatal("invalid identity was replaced")
		}
	}
}

func TestCloudCredentialIdentityReadFailureDoesNotRecreate(t *testing.T) {
	path := fixtureCredentialDevicePath(t)
	t.Setenv(cloudCredentialKeyEnvVar, "")
	if err := os.MkdirAll(path, 0o700); err != nil {
		t.Fatal(err)
	}
	if _, err := authServiceEnv(RuntimeConfig{}, RuntimePaths{}); err == nil {
		t.Fatal("unreadable identity did not fail")
	}
	info, err := os.Stat(path)
	if err != nil || !info.IsDir() {
		t.Fatal("unreadable identity was replaced")
	}
}

func TestCustomCloudCredentialKeyDoesNotRequireDeviceIdentity(t *testing.T) {
	path := fixtureCredentialDevicePath(t)
	writeCredentialIdentityFixture(t, path, "invalid-json")
	t.Setenv(cloudCredentialKeyEnvVar, "fixture-custom-key")
	if authCloudKeyForTest(t, "local") != "fixture-custom-key" {
		t.Fatal("explicit custom encryption key was changed")
	}
}

func TestCloudCredentialIdentityConcurrentCreationKeepsOneKey(t *testing.T) {
	path := fixtureCredentialDevicePath(t)
	t.Setenv(cloudCredentialKeyEnvVar, "")
	type result struct {
		key string
		err error
	}
	results := make(chan result, 16)
	for i := 0; i < cap(results); i++ {
		go func() {
			key, err := cloudCredentialKey()
			results <- result{key, err}
		}()
	}
	var first string
	for i := 0; i < cap(results); i++ {
		got := <-results
		if got.err != nil {
			t.Fatal(got.err)
		}
		if first == "" {
			first = got.key
		}
		if got.key != first {
			t.Fatal("concurrent startup generated different device keys")
		}
	}
	if desktopCloudKeyForTest(t, path) != first {
		t.Fatal("published identity does not match the startup key")
	}
}

func TestCloudCredentialKeyUsesHostIdentityAndKeepsUsersSeparate(t *testing.T) {
	path := fixtureCredentialDevicePath(t)
	writeCredentialIdentityFixture(t, path, fixtureDesktopIdentity)
	t.Setenv(cloudCredentialKeyEnvVar, "")
	t.Setenv("HOME", filepath.Join(t.TempDir(), "service-home"))
	t.Setenv(runtimeRootEnvVar, t.TempDir())
	if authCloudKeyForTest(t, "local") != fixtureDesktopCloudKey {
		t.Fatal("service HOME or custom runtime root changed the device identity")
	}
	otherPath := fixtureCredentialDevicePath(t)
	if otherPath == path || authCloudKeyForTest(t, "local") == fixtureDesktopCloudKey {
		t.Fatal("another user shares the original user's device key")
	}
}

func TestCredentialDeviceIdentityPlatformPaths(t *testing.T) {
	home := filepath.Join("fixture", "user")
	localAppData := filepath.Join("fixture", "relocated", "Local")
	for _, tc := range []struct {
		goos         string
		localAppData string
		want         string
	}{
		{"darwin", localAppData, filepath.Join(home, "Library", "Application Support", "lazymind-desktop", "credential-device.json")},
		{"windows", localAppData, filepath.Join(localAppData, "LazyMind", "Desktop", "credential-device.json")},
		{"windows", "", filepath.Join(home, "AppData", "Local", "LazyMind", "Desktop", "credential-device.json")},
		{"linux", "", filepath.Join(home, ".config", "lazymind-desktop", "credential-device.json")},
	} {
		if credentialDeviceIdentityPathForOS(tc.goos, home, tc.localAppData) != tc.want {
			t.Fatalf("incorrect %s Desktop identity path", tc.goos)
		}
	}
}
